[package]
name = "buildkit-rs-util"
description = "BuildKit utilities for Rust"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

# This crate should not have any large dependencies, as is used by all other crates.