[package]
name = "buildkit-rs-frontend"
description = "Buildkit frontend in Rust"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
tonic = "0.9.1"
