[package]
name = "frontend"
description = "Buildkit frontend in Rust"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
tonic = "0.8.3"
